### ISSUE TITLE
CTAG / TagBar support

### ISSUE THREAD

**Issue by coderberry** [otavioschwanck/mood-nvim#11]
Hi Otavio!

I'm loving that you are still paving the path for ruby/rails devs. This project is exceptional!

I was wondering if you use ctags / tagbar? I'd like to see the structure of my ruby files but as you probably remember, I'm not super good with VIM plugins.

Is this something that you plan on adding?

**Comment by otavioschwanck** [comment]
Hi @coderberry, awesome to see you back!

About tagbar, i think SPC f o should work for you.  If not, just edit your plugins (SPC f p / plugins) file.  Add to the array:
{ 'preservim/tagbar' }

Restart vim and it will be installed.

After that, just run `:TagbarToggle`
