### ISSUE TITLE
Question: How do I go to the definition of the method I'm currently on?

### ISSUE THREAD

**Issue by coderberry** [otavioschwanck/mood-nvim#12]
Thanks again for all your help! I introduced this to my company and they are loving it!!!

**Comment by coderberry** [comment]
I found it! CTRL+]

**Comment by otavioschwanck** [comment]
> I found it! CTRL+]

you can do in different ways:

gd = go to definition
gr = references
gt = type definition.

The C-] way is not the best way to do it.

About the go to references, you can navigate the list with ]q and [q (It is a quickfix list).

You can close the quick fix list with SPC q c.

@coderberry
