### ISSUE TITLE
How to add plugins?

### ISSUE THREAD

**Issue by Rinyaresu** [otavioschwanck/mood-nvim#13]
How can I integrate plugins in this new setup?

I am encountering an issue where Lazy is unable to locate the plugins present in the path `extra/examples/plugins.lua`.

**Comment by otavioschwanck** [comment]
First of all, remove everything from packer:

```sh
rm -rf ~/.config/nvim/lua/user/lsp.lua

rm -rf ~/.config/nvim/lua/user/plugins.lua

rm -rf ~/.config/nvim/plugin/packer_compiled.lua

rm -rf ~/.local/share/nvim
```

Then, open neovim (lazy will install the plugins).

After that, press SPC f p and go to plugins.

There will be some examples there.

To see the syntax, visit: 
https://github.com/folke/lazy.nvim

**Comment by Rinyaresu** [comment]
thx
