### ISSUE TITLE
How to setup solargraph?

### ISSUE THREAD

**Issue by Rinyaresu** [otavioschwanck/mood-nvim#16]
I'm trying to use Solargraph, but I can't make it work for some reason. I've tried uninstalling the gem from my system and using only the project gem with Bundler, but the LSP isn't able to identify it. I also tried using Mason, but it still didn't work, even with the `useBundler` configuration in the `nvim/lua/user` path, it seems that the LSP is not using Bundler.

**Comment by otavioschwanck** [comment]
- remove the solargraph from Mason
- Install with the version that you are using (i recommend rbenv) (gem install solargraph)

it should work.

if still not work, paste the :LspInfo and :LspLog here

**Comment by Rinyaresu** [comment]
I followed your instructions, but unfortunately, it's still not working. btw I'm using asdf.

![image](https://user-images.githubusercontent.com/79602114/221180127-6ae66555-eefb-4bec-aed0-7c430fb100fd.png)

The log is not being updated after removing solargraph from mason. The log below is from the previous version, before the removal.

```

[START][2023-02-23 22:52:20] LSP logging initiated
[ERROR][2023-02-23 22:52:20] .../vim/lsp/rpc.lua:734	"rpc"	"solargraph"	"stderr"	"Solargraph is listening on stdio PID=986256\n"
[ERROR][2023-02-23 22:52:20] .../vim/lsp/rpc.lua:734	"rpc"	"solargraph"	"stderr"	"(none):166: warning: string literal in condition\n"
[ERROR][2023-02-23 22:52:20] .../vim/lsp/rpc.lua:734	"rpc"	"solargraph"	"stderr"	"(none):166: warning: string literal in condition\n"
[ERROR][2023-02-23 22:52:26] .../vim/lsp/rpc.lua:734	"rpc"	"solargraph"	"stderr"	"--auto-correct is deprecated; use --autocorrect instead.\n"
[ERROR][2023-02-23 22:52:26] .../vim/lsp/rpc.lua:734	"rpc"	"solargraph"	"stderr"	"#<Thread:0x00007f99bd7abd78 /home/kaique/.local/share/nvim/mason/packages/solargraph/gems/solargraph-0.48.0/lib/solargraph/language_server/host/message_worker.rb:43 run> terminated with exception (report_on_exception is true):\n"
[ERROR][2023-02-23 22:52:26] .../vim/lsp/rpc.lua:734	"rpc"	"solargraph"	"stderr"	"#<Thread:0x00007f99bd705b08 /home/kaique/.local/share/nvim/mason/packages/solargraph/gems/solargraph-0.48.0/lib/solargraph/language_server/host/diagnoser.rb:45 run> terminated with exception (report_on_exception is true):\n"
[ERROR][2023-02-23 22:52:26] .../vim/lsp/rpc.lua:734	"rpc"	"solargraph"	"stderr"	"/home/kaique/.local/share/nvim/mason/packages/solargraph/gems/rubocop-1.46.0/lib/rubocop/feature_loader.rb:46:in `rescue in rescue in load': cannot load such file -- rubocop-rspec (LoadError)\n"

```

In my project, I am using version 0.38.0 of Solargraph. However, Mason was using version 0.48.0

**Comment by otavioschwanck** [comment]
Try to run bundle on your project. (install mason). LSP will not work when the bundle is not updated.

If not work, the problem is probably because the neovim is not reconizing the asdf version of ruby for some reason. I really recommend switching from asdf to rbenv because it handles ruby better
