### ISSUE TITLE
Failed to run `config` for harpoon

### ISSUE THREAD

**Issue by jonmaciel** [otavioschwanck/mood-nvim#23]
This is happening after I update the nvim last week.
I tried many times to reinstall all the Mood, but didn't work
I tried to update `fb` and  `ripgrep`
But didn't worked either.

Any clues?

It's also no loading the footer bar anymore. Can it be a related error?

```
Error detected while processing UIEnter Autocommands for "*"..User Autocommands for "LazyVimStarted":
Error executing lua callback: ...m/lazy/telescope.nvim/lua/telescope/_extensions/init.lua:10: 'harpoon' extension doesn't exist or isn't installed: ...re/nvim/lazy/harpoon/lua/telescope/_extensions/marks.lua:7: loop or previous error loading module 'harpoon'
stack traceback:
        [C]: in function 'error'
        ...m/lazy/telescope.nvim/lua/telescope/_extensions/init.lua:10: in function 'load_extension'
        ...m/lazy/telescope.nvim/lua/telescope/_extensions/init.lua:62: in function 'load_extension'
        ...pe-all-recent.nvim/lua/telescope-all-recent/override.lua:105: in function 'load_extension'
        ...maciel/.config/nvim/lua/mood-scripts/setup-telescope.lua:97: in function 'setup'
        /Users/jonmaciel/.config/nvim/lua/core/autocmds.lua:130: in function </Users/jonmaciel/.config/nvim/lua/core/autocmds.lua:117>
        [C]: in function 'nvim_exec_autocmds'
        ...ciel/.local/share/nvim/lazy/lazy.nvim/lua/lazy/stats.lua:24: in function 'on_ui_enter'
        ...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/config.lua:254: in function <...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/config.lua:253>
```

Second error:

```
Failed to run `config` for harpoon

...ciel/.local/share/nvim/lazy/harpoon/lua/harpoon/init.lua:16: Invalid 'event': 'BufLeave, VimLeave'

# stacktrace:
  - /harpoon/lua/harpoon/init.lua:16
  - ~/.config/nvim/lua/plugins/harpoon.lua:5 _in_ **config**
  - /telescope.nvim/lua/telescope/_extensions/init.lua:8 _in_ **load_extension**
  - /telescope.nvim/lua/telescope/_extensions/init.lua:62 _in_ **load_extension**
  - /telescope-all-recent.nvim/lua/telescope-all-recent/override.lua:105 _in_ **load_extension**
  - ~/.config/nvim/lua/mood-scripts/setup-telescope.lua:97 _in_ **setup**
  - ~/.config/nvim/lua/core/autocmds.lua:130
```

![image](https://github.com/otavioschwanck/mood-nvim/assets/12803978/24d64328-a6ff-448c-ae4b-750600c53bc2)

![image](https://github.com/otavioschwanck/mood-nvim/assets/12803978/94d609df-928c-4231-9887-37487ac54e35)

**Comment by otavioschwanck** [comment]
Fala jonzera, tenta dar um update de novo ai com `SPC h u`

**Comment by otavioschwanck** [comment]
@jonmaciel this erros is because you don't have pynvim installed.  Please install with:
pip (or pip3) install pynvim

**Comment by jonmaciel** [comment]
E ae, Tavin!  Pior que tinha o pynvim instalado.
Tentei atualizar o pip e reinstalar o `pynvim`, depois reinstalar todo o Mood, mesmo assim continuo com o mesmo erro.

Se serve como pista, eu atualizei a versão do macOS e também mandei atualizar quase tudo que foi instalado pelo brew

**Comment by jonmaciel** [comment]
@otavioschwanck  E ae, Tavin! Pior que tinha o pynvim instalado.
Tentei atualizar o pip e reinstalar o pynvim, depois reinstalar todo o Mood, mesmo assim continuo com o mesmo erro.

Se serve como pista, eu atualizei a versão do macOS e também mandei atualizar quase tudo que foi instalado pelo brew

No geral está funcionando tudo certo, só está sem a barra de rodapé e o telescope está um pouco mais lento.
Mas consigo continuar o Mood no dia a dia

**Comment by jonmaciel** [comment]
@otavioschwanck vi que você mandou um commit há pouco, mandei um `SPC h u` e corrigiu tudo!

Valeeeeu Tavin! Ta bem mais rápido até o telescope agora

**Comment by jonmaciel** [comment]
Só está aparecendo esse warning na parte de baixo quando uso o telescope, mas está funcionando certinho

![image](https://github.com/otavioschwanck/mood-nvim/assets/12803978/7a323792-1bde-4b29-85cf-0650a2aca5ed)

**Comment by otavioschwanck** [comment]
> Só está aparecendo esse warning na parte de baixo quando uso o telescope, mas está funcionando certinho
> 
> ![image](https://user-images.githubusercontent.com/12803978/282071657-7a323792-1bde-4b29-85cf-0650a2aca5ed.png)

tenta atualizar o nvim: brew upgrade nvim

**Comment by jonmaciel** [comment]
Já está atualizado
![image](https://github.com/otavioschwanck/mood-nvim/assets/12803978/91b0d544-6cb0-425e-bdb6-a115592b3e53)

**Comment by jonmaciel** [comment]
Já está atualizado
![image](https://github.com/otavioschwanck/mood-nvim/assets/12803978/a4f1e94d-18d5-4414-9969-d59b7619634d)

**Comment by jonmaciel** [comment]
@otavioschwanck Eu estou com o pynvim instalado, mesmo assim recebo essa mensagem de erro.
Eu preciso informar em algum lugar o diretório de instalação do pynvim?

![image](https://github.com/otavioschwanck/mood-nvim/assets/12803978/61b6c42c-1252-4057-9731-2c385819a6f3)

**Comment by otavioschwanck** [comment]
> @otavioschwanck Eu estou com o pynvim instalado, mesmo assim recebo essa mensagem de erro. Eu preciso informar em algum lugar o diretório de instalação do pynvim?
> 
> ![image](https://user-images.githubusercontent.com/12803978/282495885-61b6c42c-1252-4057-9731-2c385819a6f3.png)

subi um fix, atualiza ai com SPC h u.  (Talvez seja necessário rodar `:Lazy update harpoon`

**Comment by jonmaciel** [comment]
@otavioschwanck Funcionou! Valeu, Tavin!
