### ISSUE TITLE
[request] make the config compatible with NVIM_APPNAME

### ISSUE THREAD

**Issue by twnaing** [otavioschwanck/mood-nvim#24]
I use git to clone and open it with NVIM_APP=mood-nvim

Installation has problems with tmux-awesome-manager and other config related errors.

Update also doesn't work.

Do you have plan to make this config compatible with neovim running with NVIM_APPNAME?

**Comment by otavioschwanck** [comment]
i will take a look 

EDIT:

tried with NVIM_APPNAME and worked fine.  What version of neovim are you using?  And what is the OS?

Me here:

nvim --version
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.0-beta3

    arquivo vimrc de sistema: "$VIM/sysinit.vim"
            padrão para $VIM: "/opt/homebrew/Cellar/neovim/0.9.2/share/nvim"

Run :checkhealth for more info

**Comment by twnaing** [comment]
`SPC h u` gives this error

> zsh:cd:1: no such file or directory: /home/user/.config/nvim

Running `NVIM_APPNAME=mood-nvim nvim` causes nvim to look for mood-nvim directory under `~/.config` `~/.local/share/ `~`/.local/state` `~/.cache/`. So the lua scripts or installation script need to aware of the `NVIM_APPNAME` too.

Here is the relevant documentation https://neovim.io/doc/user/starting.html#%24NVIM_APPNAME

**Comment by otavioschwanck** [comment]
@twnaing done!
