### ISSUE TITLE
Format on save?

### ISSUE THREAD

**Issue by Rinyaresu** [otavioschwanck/mood-nvim#9]
Olá venho usando sua dotfiles para desenvolvimento com RoR e queria saber se existe format on save na sua configuração? desde já obg pelo projeto.

**Comment by otavioschwanck** [comment]
Olá, tudo bem?

Tem sim.  Não sei o quão desatualizado tá seu config.lua, se quiser reconfigurar ele, rode :CleanConfigs e reinicie o neovim .

Acessando suas configurações privadas (SPC f p), você vai ver:

```lua
-- autocmd array(AutoCmd, pattern, callback)
local autocommands = {
  { {"FileType"}, two_space_languages, function() vim.cmd('setlocal shiftwidth=2 tabstop=2') end },
  { {"FileType"}, four_space_languages, function() vim.cmd('setlocal shiftwidth=2 tabstop=2') end },
  { {'BufWritePre'}, {"*.tsx", "*.ts", "*.jsx", "*.js"}, function() vim.cmd("PrettierAsync") end, } -- Run Command before save (can be any command)
}
```

No caso do ultimo argumento da table, antes de salvar um arquivo (BufWritePre), do tipo *.tsx, *.ts, *jsx, *js, ele roda o comando PrettierAsync.

Se quiser fazer um para o rubocop por exemplo, basta:
```lua
 { {'BufWritePre'}, {"*.rb"}, function() vim.cmd(":w | :silent !bundle exec rubocop -A %") end, }
 ```

**Comment by Rinyaresu** [comment]
Obrigado, e parabéns pelo projeto.
